In [ ]:
import numpy as np

In [ ]:
arr=np.array([[1,2],[3,4]])
print(arr)
print(type(arr))
print(arr.shape) # check shape of array

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
(2, 2)


In [ ]:
arr.ndim # dimension of array

2

In [ ]:
print(arr.data) #memory location of array
print(id(arr))

139768543366768


Random number generate

In [ ]:
from numpy import random
x=random.randint(100) # generate random no. in between 1 to 100 including 1 and 100
print(x)

53


In [ ]:
print(type(x))

<class 'int'>


In [ ]:
#generate random float (generate random float in between 0 to 1)
y=random.rand() 
print(y)

0.9082054364996627


In [ ]:
#generate random array
x=random.randint(5,10,size=(2,4)) # size will give 2X4  matrix

In [ ]:
print(x)

[[5 5 6 7]
 [6 9 7 5]]


Scalar in numpy

In [ ]:
# array to number
inputarr=np.array([7])
print(inputarr)
print(type(inputarr))

#asscalar() method --> can only apply in 1-d array with 1 element
outputarr=np.asscalar(inputarr)
print(outputarr)
print(type(outputarr))

[7]
<class 'numpy.ndarray'>
7
<class 'int'>


<ipython-input-36-b15105f798b2>:7: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
  outputarr=np.asscalar(inputarr)


vector in numpy

In [ ]:
#list to array
#create 1-D list horizontally
list1=[1,23,5]
list2=[[10],
       [20],
       [30]]
print(list1)
print(list2)
print(len(list1))
print(len(list2))

vector1=np.array(list1)
vector2=np.array(list2)
print("Horizontal vector",vector1)
print("vertical vector",vector2)

print(type(vector1))
print(type(vector2))

[1, 23, 5]
[[10], [20], [30]]
3
3
Horizontal vector [ 1 23  5]
vertical vector [[10]
 [20]
 [30]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


matrix using numpy

In [ ]:
a=np.matrix('1 25;3 4')
print(a)
print(a.shape)
print(type(a))

b=np.array(a)
print(b)
print(type(b))

[[ 1 25]
 [ 3  4]]
(2, 2)
<class 'numpy.matrix'>
[[ 1 25]
 [ 3  4]]
<class 'numpy.ndarray'>


Matrix Multiplication

In [ ]:
A=5
B=[[20,4],[6,9]]
print(np.dot(A,B))

[[100  20]
 [ 30  45]]


In [ ]:
A=[[5,6],[8,9]]
B=[[9,7],[8,7]]
print(np.dot(A,B))

[[ 93  77]
 [144 119]]
